### ISSUE TITLE
Failure when cooking a workspace with local crates that are renamed

### ISSUE THREAD

**Issue by Veetaha** [LukeMathWalker/cargo-chef#103]
Suppose we have a crate `foo`

```toml
name = "foo"
version = "0.1.2"
```

and we have a crate `bar`

```toml
name = "bar"
version = "0.1.2"

[dependencies]
foo2 = { path = "../foo", version = "^0.1.2", package = "foo" }
```

This project layout where a local crate depends on other local crate that is renamed doesn't work with the logic here:
https://github.com/LukeMathWalker/cargo-chef/blob/30e5b862483790f13c337acacf2c60f6cde7ac43/src/skeleton/version_masking.rs#L3-L22

`cargo chef` replaces the versions of all local crates with `0.0.1`, however it doesn't modify the version requirement in bar's `[dependencies]` for `foo2`, so `cargo chef cook` fails with

```
error: failed to select a version for the requirement `foo = "^0.1.2"`
candidate versions found which didn't match: 0.0.1
```
