### ISSUE TITLE
`no_std` builds

### ISSUE THREAD

**Issue by mrd0ll4r** [LukeMathWalker/cargo-chef#131]
Hey,

I've been using `cargo chef` with great success for various projects :)
This time I wanted to try some embedded programming for an AVR mcu with Rust.
For that, I set up an empty-ish example project like so:
```
cargo install cargo-generate
cargo generate --git https://github.com/Rahix/avr-hal-template.git
```
I called it `rust-avr-test`.

Building this in Docker works, you just need a bunch of dependencies, compilers, nightly toolchain and whatnot, but it works.
The Dockerfile I use for that looks like this:
```
FROM rust:1-buster AS chef

RUN apt-get update && apt-get -y install binutils gcc-avr avr-libc 

RUN rustup toolchain install nightly-2022-05-10
RUN rustup default nightly-2022-05-10
RUN rustup component add rust-src
RUN cargo version

RUN cargo install cargo-chef
```

On top of that I then tried my usual builder Dockerfile, with `cargo chef`, which looks somewhat like this:
```
FROM avr-builder:latest AS chef

FROM chef AS planner
COPY . .

WORKDIR /rust-avr-test
RUN cargo chef prepare --recipe-path recipe.json

FROM chef as builder
WORKDIR /rust-avr-test
COPY --from=planner /shack/rust-avr-test/recipe.json recipe.json
COPY ./rust-avr-test/avr-specs ./avr-specs
COPY ./rust-avr-test/rust-toolchain.toml .
#COPY ./rust-avr-test/src/main.rs ./src/main.rs
RUN cargo chef cook --release --recipe-path recipe.json

WORKDIR /
COPY . .
WORKDIR /rust-avr-test
RUN cargo build --release
```
(or something like that)

`cargo chef prepare` works, but `cargo chef cook` fails.
It compiles all the dependencies just fine, but then it tries to build the project, which fails because of `no_std` and a missing panic handler:
```
   Compiling rust-avr-test v0.0.1 (/rust-avr-test)
error[E0463]: can't find crate for `std`
  |
  = note: the `avr-atmega328p-5093738666997825484` target may not support the standard library
  = note: `std` is required by `rust_avr_test` because it does not declare `#![no_std]`
  = help: consider building the standard library from source with `cargo build -Zbuild-std`

error: `#[panic_handler]` function required, but not found

For more information about this error, try `rustc --explain E0463`.
error: could not compile `rust-avr-test` due to 2 previous errors
thread 'main' panicked at 'Exited with status code: 101', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/cargo-chef-0.1.35/src/recipe.rs:145:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
The command '/bin/sh -c cargo chef cook --release --recipe-path recipe.json' returned a non-zero code: 101
```

All that stuff is handled in `main.rs`, which looks like this by default:
```rust
#![no_std]
#![no_main]

use panic_halt as _;

#[arduino_hal::entry]
fn main() -> ! {
    let dp = arduino_hal::Peripherals::take().unwrap();
    let pins = arduino_hal::pins!(dp);

    /*
     * For examples (and inspiration), head to
     *
     *     https://github.com/Rahix/avr-hal/tree/main/examples
     *
     * NOTE: Not all examples were ported to all boards!  There is a good chance though, that code
     * for a different board can be adapted for yours.  The Arduino Uno currently has the most
     * examples available.
     */

    let mut led = pins.d13.into_output();

    loop {
        led.toggle();
        arduino_hal::delay_ms(1000);
    }
}
```

So I tried just copying that into the container, hoping it would be found and stuff would work, but the result is the same...

The template-generated Cargo.toml looks like this:
```toml
[package]
name = "rust-avr-test"
version = "0.1.0"
authors = [""]
edition = "2021"
license = "MIT OR Apache-2.0"

[[bin]]
name = "rust-avr-test"
test = false
bench = false

[dependencies]
panic-halt = "0.2.0"
ufmt = "0.1.0"
nb = "0.1.2"
embedded-hal = "0.2.3"

[dependencies.arduino-hal]
git = "https://github.com/rahix/avr-hal"
rev = "d0d2f243bd3e10b49f6a78d44839a6caa8be7d43"
features = ["arduino-nano"]

# Configure the build for minimal size - AVRs have very little program memory
[profile.dev]
panic = "abort"
lto = true
opt-level = "s"

[profile.release]
panic = "abort"
codegen-units = 1
debug = true
lto = true
opt-level = "s"
```

The point of cross-compiling inside a container is to not have a bunch of project-specific packages and tools flying around on my host, and of course to make stuff run in CI.

Any help would be greatly appreciated :)
Best,
Leo
