### ISSUE TITLE
Building with chef fails on "crate-types" error

### ISSUE THREAD

**Issue by yurado** [LukeMathWalker/cargo-chef#290]
Using Chef `0.1.69`, rustup: `1.27.1`,  and Rust: `1.80.0`, I get the following error:
```
 > [builder 3/5] RUN cargo chef cook --workspace --release --recipe-path recipe.json:
0.373 error: failed to parse manifest at `/app/my_project/Cargo.toml`
0.373
0.373 Caused by:
0.373   the target `my_project` is a binary and can't have any crate-types set (currently "bin")
0.377 thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-chef-0.1.69/src/recipe.rs:218:27:
0.377 Exited with status code: 101

```

**Comment by Callum-A** [comment]
Same issue here, my solution was to set chef manually to 0.1.68 for now!

**Comment by mikevercoelen** [comment]
@LukeMathWalker 

Can you provide more context? Is this going to be properly fixed? We have production outage and we wasted time investigating on our end.

**Comment by mikevercoelen** [comment]
This is what worked for us, pin the version in the Dockerfile:

(if you are using Fly.io and therefore ended up using this library)

```
FROM lukemathwalker/cargo-chef:0.1.68-rust-latest AS chef
```

**Comment by miend** [comment]
> Same issue here, my solution was to set chef manually to 0.1.68 for now! `cargo install --version 0.1.68 cargo-chef`
 
+1 to problem, and this solution worked for me on Fly.io depot builds, rust 1.84

**Comment by zakhenry** [comment]
in my Dockerfile, my workaround was to pin version with 

```dockerfile
# version pinned due to https://github.com/LukeMathWalker/cargo-chef/issues/290
RUN cargo install cargo-chef@0.1.68
```

**Comment by WorkingRobot** [comment]
The reason for this failure is due to `cargo-manifest` adding back in some properties that cargo itself doesn't support.
In the error here, it's due to the addition of `crate-type = ["bin"]` into the `[[bin]]` when [this shouldn't be added for binaries](https://doc.rust-lang.org/cargo/reference/cargo-targets.html#the-crate-type-field).

For reference, here's a snippet of the offending code in my project:
```toml
[[bin]]
path = "src/main.rs"
name = "some-package"
plugin = false # This causes a warning now, too
proc-macro = false
edition = "2021"
required-features = []
crate-type = ["bin"] # This shouldn't be here by default!

[package]
name = "some-package"
edition = "2021"
version = "0.0.1"
build = "build.rs"
authors = ["Author A <a@example.com>"]
description = "some description"
repository = "https://github.com/..."

[dependencies]
# continued
```
