### ISSUE TITLE
Warning: `unused manifest key` `plugin`

### ISSUE THREAD

**Issue by josecelano** [LukeMathWalker/cargo-chef#301]
Relates to: https://github.com/torrust/torrust-tracker/issues/1230

When I run `cargo chef` I get warnings because the modified `Cargo.toml` files contains and unused manifest key called `plugin`:

```toml
[lib]
plugin = false

[[bin]]
plugin = false

[[bench]]
plugin = false

[[test]]
plugin = false

# ...
```

I guess is something you used that cargo does not but I thought it was something wrong in my configuration.
