### ISSUE TITLE
Ignore local path dependencies

### ISSUE THREAD

**Issue by JonasKs** [LukeMathWalker/cargo-chef#307]
Hi!

I was wondering if you’d be interested in a PR to remove local path dependencies? Or if there is a better solution to keep external dependencies cached in a monorepo?

I have a workspace with this structure:

- services
  - service1
    - api
    - databae
    - tasks
  - service2
    - api
- libs
  - config
  - utils
  - otel

Some services, e.g. `service1-api` depends on a lot of external dependencies, but also local dependencies such as `config` or `utils`. These dependencies change all the time, since it’s a large monorepo. This invalidates my cache, and I have to download and build all external dependencies as well, for each build. 

I would like to use cargo chef to only cache _external_ dependencies. I envision this could be achieved by having a `—no-local` (or similar) flag, which removes any `dep = {path = “..”}` dependency. 

My current Docker image: 
```Dockerfile
# Good article on why we use cargo chef: https://www.lpalmieri.com/posts/fast-rust-docker-builds/#caching-rust-builds
FROM docker.io/rust:1-alpine AS chef
RUN apk add --no-cache \
    # Required for cargo-chef
    musl-dev openssl-dev \
    # required for openSSL linking
    openssl-libs-static \
    # Required for TLS
    ca-certificates \
    && update-ca-certificates
RUN cargo install cargo-chef
WORKDIR /app

# Generate/prepare recipe. Changes to the code will invalidate cache for planner,
# but it will not invalidate the cache for the builder container, as long as the checksum of the
# recipe.json file does not change.
FROM chef AS planner
COPY . .
RUN cargo chef prepare --bin service1_api

# Read recipe, might be cached
FROM chef AS builder
COPY --from=planner /app/recipe.json recipe.json
# Build _dependencies_ - This is the caching Docker layer
RUN cargo chef cook --bin service1_api --release --recipe-path recipe.json

# Copy over all files required for a build of this app, given the dependencies are already built
COPY . .

RUN SQLX_OFFLINE=true cargo build --release --bin service1_api

FROM scratch AS runtime
WORKDIR /app

COPY --from=builder /app/target/release/service1_api /app/service1_api
COPY --from=builder 
# Scratch don't have CA certs, so we copy them from chef
COPY --from=chef /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

ENTRYPOINT ["/app/service1_api"]
```

and my workflow:

```yaml

      - name: Build and push
        id: build_and_push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: services/${{ steps.extract.outputs.docker-path }}/ci/docker/Dockerfile
          push: true
          cache-to: type=gha,scope=${{ steps.extract.outputs.service-name }},mode=max,timeout=168h
          cache-from: type=gha,scope=${{ steps.extract.outputs.service-name }}
          tags: ${{ steps.meta.outputs.tags }}
```

**Comment by JonasKs** [comment]
I think the cache invalidation is actually caused by my setup, where I have:

```toml
[[bin]]
name = "service1_api"
path = "src/main.rs"

[lib]
name = "service1_api_lib"
path = "src/lib.rs"
```
I have both a lib and bin due to some end2end tests. This generates a new `.lock`-file, which in turn invalidates the cache.

So i'll strip that out of my services before I run cargo chef. 😊
