### ISSUE TITLE
Path/workspace dependencies – failed to read Cargo.toml

### ISSUE THREAD

**Issue by oeed** [LukeMathWalker/cargo-chef#51]
I have a monorepo with multiple binaries sharing a set of common custom libraries, structured as so:
```
binary_a/
  Cargo.toml
  src/
binary_b/
  Cargo.toml
  src/
lib/
  lib_a/
    Cargo.toml
    src/
  lib_b/
    Cargo.toml
    src/
```

Each library in `lib` has its own dependencies and not every binary needs every library. I'm rather unclear if this is actually the best way to do it (please correct me if so), but each binary is configured as a workspace with each library it needs as a member. I'd originally placed this workspace at the root level, but upon further reading that seems to be incorrect.

Each binary Cargo.toml looks somewhat like this:

```toml
[workspace]
members = [
  "../lib/lib_a"
]

[package]
name = "binary_a"

[dependencies]
serde = "~1"
lib_a = {path = "../lib/lib_a"}
```

`cargo cook prepare` seems to work with this structure, the output `contents` field looks largely like the above toml, notably containing these local dependencies as such:
```toml
[dependencies.lib_a]
path = "../lib/lib_a"
features = []
optional = false
```

When it comes to `cargo chef cook` though, it fails because the `lib/` folder isn't present: `error: failed to read /usr/src/app/lib/lib_a/Cargo.toml`

What am I doing wrong here? It's important to note that I _don't want to cache the `lib/` folder_. 99% of the code is in that folder, so I only want to cache external (i.e. non-lib/) dependencies.

It's probably more my workspace/crate setup that's at fault more than anything else, but happy to add further details as required.

Cheers
