### ISSUE TITLE
A very small image with very fast build

### ISSUE THREAD

**Issue by azzamsa** [LukeMathWalker/cargo-chef#62]
After reading [5x Faster Rust Docker Builds with cargo-chef](https://www.lpalmieri.com/posts/fast-rust-docker-builds/). Indeed, it was faster. But still produce big image. So I decide to use `scratch` as base image.

`cargo-chef` combined with `scratch` is awesome.

```
ARG BASE_IMAGE=rust:1.52-slim-buster
ARG VCS_REVISION

FROM $BASE_IMAGE as planner
WORKDIR app
RUN cargo install cargo-chef --version 0.1.20
COPY . .
RUN cargo chef prepare  --recipe-path recipe.json

FROM $BASE_IMAGE as cacher
WORKDIR app
RUN cargo install cargo-chef --version 0.1.20
COPY --from=planner /app/recipe.json recipe.json
RUN cargo chef cook --release --recipe-path recipe.json

FROM $BASE_IMAGE as builder
WORKDIR app
COPY . .
# Copy over the cached dependencies
COPY --from=cacher /app/target target
COPY --from=cacher $CARGO_HOME $CARGO_HOME
# We need static linking for smaller image.
RUN rustup target add x86_64-unknown-linux-musl
ARG VCS_REVISION
# `cargo build` doesn't work in static linking, need `cargo install`
RUN VCS_REVISION=$VCS_REVISION cargo install --target x86_64-unknown-linux-musl --path .

FROM scratch
WORKDIR app
COPY --from=builder /usr/local/cargo/bin/awesomeapp .
CMD ["./awesomeapp"]
```

---

Size comparison, with these dependencies:

```toml
rocket = { git = "https://github.com/SergioBenitez/Rocket", rev = "3a7559e", default-features = false }
rocket_contrib = { git = "https://github.com/SergioBenitez/Rocket", rev = "3a7559e" }
serde = { version = "1.0", features = ["derive"] }
```

- `scratch` : 8.63MB
- `rust:1.52-slim-buster`: 629MB
- `rust:1.52`: 1.24GB
