### ISSUE TITLE
/usr/local/bin/pipeline: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by SorenHolstHansen** [LukeMathWalker/cargo-chef#98]
I am using the basic example in the readme, that is
```
FROM lukemathwalker/cargo-chef:latest-rust-1.53.0 AS chef
WORKDIR /app

FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder 
COPY --from=planner /app/recipe.json recipe.json
# Build dependencies - this is the caching Docker layer!
RUN cargo chef cook --release --recipe-path recipe.json
# Build application
COPY . .
RUN cargo build --release --bin pipeline

# We do not need the Rust toolchain to run the binary!
FROM debian:buster-slim AS prod
WORKDIR /app
COPY --from=builder /app/target/release/pipeline /usr/local/bin
ENTRYPOINT ["/usr/local/bin/pipeline"]
```
And this worked fine for the rust project you get when running `cargo new pipeline`. However, now i put some more stuff in, and now the structure is like the following
```
src/
- main.rs
- lib.rs
  dk/
  -  mod.rs
    oda/
    - mod.rs
    - ...some other stuff
```
And my cargo.toml looks like this
```toml
[package]
name = "pipeline"
version = "0.1.0"
authors = ["..."]
edition = "2018"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "pipeline"

[dependencies]
sqlx = { version = "0.5", features = [ "runtime-tokio-rustls", "postgres", "macros", "migrate", "time" ] }
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde = "1.0"
chrono = { version = "0.4", features = ["serde"] }
anyhow = "1.0"
quick-xml = { version = "0.22", features = ["serialize"] }
```
Now when i run `docker build -t pipeline .` and then `docker run pipeline` i get
```
/usr/local/bin/pipeline: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```
I don't know what is going wrong. I have a more basic Dockerfile.local that looks like this
```
FROM rust:latest

WORKDIR /app

RUN cargo install cargo-watch
```
Just for development purposes, and when running `docker build -t pipeline_dev -f Dockerfile.local .` and then `docker run --rm -it --mount type=bind,source="$(pwd)",target=/app pipeline_dev` it works fine, and i can run `cargo run` inside that shell.

So I think that the problem is with cargo-chef, however I might very well be wrong.

Anyone know what is going wrong?
